package com.dev.userauthservice.constants;

/**
 * Application-wide constants
 * Generated by Bootbase CLI on 2025-10-26 14:23:09
 * @author patmesh
 */
public final class ApplicationConstants {

    private ApplicationConstants() {
        // Private constructor to prevent instantiation
    }

    // API Constants
    public static final String API_VERSION = "/api/v1";
    public static final String DEFAULT_PAGE_SIZE = "20";
    public static final String MAX_PAGE_SIZE = "100";

    // Response Messages
    public static final String SUCCESS_MESSAGE = "Operation completed successfully";
    public static final String ERROR_MESSAGE = "An error occurred while processing your request";
    public static final String NOT_FOUND_MESSAGE = "Resource not found";
    public static final String VALIDATION_ERROR_MESSAGE = "Validation failed";

    // Date Formats
    public static final String DATE_TIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ss";
    public static final String DATE_FORMAT = "yyyy-MM-dd";

    // Headers
    public static final String CORRELATION_ID_HEADER = "X-Correlation-ID";
    public static final String REQUEST_ID_HEADER = "X-Request-ID";
}