package com.dev.userauthservice.controller;

import com.dev.userauthservice.dto.response.APIResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

/**
 * Base controller with common functionality
 * Generated by Bootbase CLI on 2025-10-26 14:23:09
 * @author patmesh
 */
public abstract class BaseController {

    protected <T> ResponseEntity<APIResponse<T>> success(T data) {
        return ResponseEntity.ok(APIResponse.success(data));
    }

    protected <T> ResponseEntity<APIResponse<T>> success(T data, String message) {
        return ResponseEntity.ok(APIResponse.success(data, message));
    }

    protected <T> ResponseEntity<APIResponse<T>> created(T data) {
        return ResponseEntity.status(HttpStatus.CREATED)
            .body(APIResponse.success(data, "Account created successfully"));
    }

    protected <T> ResponseEntity<APIResponse<T>> error(String message) {
        return ResponseEntity.badRequest()
            .body(APIResponse.error(message));
    }

    protected <T> ResponseEntity<APIResponse<T>> error(HttpStatus status, String message) {
        return ResponseEntity.status(status)
            .body(APIResponse.error(message));
    }
}