---
apiVersion: v1
kind: ConfigMap
metadata:
  name: janusgraph-config
  namespace: default
data:
  janusgraph.properties: |
    storage.backend=cql
    storage.hostname=cassandra
    storage.cql.keyspace=janusgraph
    cache.db-cache=true
    cache.db-cache-clean-wait=20
    cache.db-cache-time=180000
    cache.db-cache-size=0.25
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: janusgraph
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: janusgraph
  template:
    metadata:
      labels:
        app: janusgraph
    spec:
      containers:
      - name: janusgraph
        image: janusgraph/janusgraph:latest
        ports:
        - containerPort: 8182
        env:
        - name: JANUS_PROPS_TEMPLATE
          value: "cql"
        - name: janusgraph.storage.backend
          value: "cql"
        - name: janusgraph.storage.hostname
          value: "cassandra"
        - name: JAVA_OPTIONS
          value: "-Xms512m -Xmx512m"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: config-writable
          mountPath: /etc/opt/janusgraph
      volumes:
      - name: config-source
        configMap:
          name: janusgraph-config
      - name: config-writable
        emptyDir: {}
      initContainers:
      - name: init-config
        image: busybox
        command: ['sh', '-c', 'cp /tmp/janusgraph-config/janusgraph.properties /etc/opt/janusgraph/janusgraph.properties && ls -la /etc/opt/janusgraph/']
        volumeMounts:
        - name: config-source
          mountPath: /tmp/janusgraph-config
        - name: config-writable
          mountPath: /etc/opt/janusgraph
      - name: wait-for-cassandra
        image: busybox
        command: ['sh', '-c', 'until nc -z cassandra 9042; do echo waiting for cassandra; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: janusgraph
  namespace: default
spec:
  selector:
    app: janusgraph
  ports:
  - port: 8182
    targetPort: 8182
  type: ClusterIP
