apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5.12.0
          env:
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"
            - name: NEO4J_AUTH
              value: "neo4j/password"
            - name: NEO4J_dbms_memory_pagecache_size
              value: "512M"
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "512M"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "512M"
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  type: NodePort
  selector:
    app: neo4j
  ports:
    - name: http
      port: 7474
      targetPort: 7474
      nodePort: 30074
    - name: bolt
      port: 7687
      targetPort: 7687
      nodePort: 30687
