---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: docker.io/patmeshs/notification-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8994
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "social_notifications"
        - name: DB_USER
          value: "socialfeed"
        - name: DB_PASSWORD
          value: "dev123"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379" 
        resources:
          requests:
            memory: "196Mi"
            cpu: "50m"
          limits:
            memory: "384Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: default
spec:
  selector:
    app: notification-service
  ports:
  - port: 8994
    targetPort: 8994
  type: ClusterIP
